# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b71e3e7fc5bc2f6656c5064822f0d7bb9edf04b0e95843344e87a08a8692c4661bdd9470d78e61ae823751cf2c0bb9686de7b3b64f5920478d025b2417e3969

test:
  secret_key_base: 117aabb218f3ee0d31dc419e90e0c263b77cbb93a4a5f304234ad3d2b23513ed3d6e80583452ed6638c21077ee528c614ebec7aaafc421fe8f1e8834f9363adb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
